#!/bin/sh
# shellcheck disable=SC2155

# Add all directories in `~/.local/bin` to $PATH
export PATH="$PATH:$(find ~/.local/bin -type d | paste -sd ':' -)"

# Default apps
export EDITOR="nvim"
export TERMINAL="alacritty"
export TERMINAL_PROG="alacritty"
export BROWSER="brave"

# Fixing paths
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export GOPATH="$XDG_DATA_HOME/go"
export GOMODCACHE="$XDG_CACHE_HOME/go/mod"
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export INPUTRC="$XDG_CONFIG_HOME/shell/inputrc"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$XDG_DATA_HOME/history"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export MBSYNCRC="$XDG_CONFIG_HOME/mbsync/config"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"

# Other program settings
export DICS="/usr/share/stardict/dic/"
export SUDO_ASKPASS="$HOME/.local/bin/dmenupass"
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"
export LESS="-R"
export LESS_TERMCAP_mb=$(printf '\33[01;31m')
export LESS_TERMCAP_md=$(printf '\33[01;36m')
export LESS_TERMCAP_me=$(printf '\33[0m')
export LESS_TERMCAP_so=$(printf '\33[01;47;34m')
export LESS_TERMCAP_se=$(printf '\33[0m')
export LESS_TERMCAP_us=$(printf '\33[01;32m')
export LESS_TERMCAP_ue=$(printf '\33[0m')
export QT_QPA_PLATFORMTHEME="gtk2"

# Start graphical server on user's current TTY if not already running
[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx "$XINITRC"

# Change Caps Lock to Escape if in TTY and no password required
sudo -n loadkeys "$XDG_DATA_HOME/loadkeys/ttymaps.kmap" 2>/dev/null
